#!/usr/bin/env python3
"""Repack the small C audit corpus from immutable historical fixture bytes.

The primary corpus is regenerated by regenerate-wasm.py. These independent
C outputs are retained as an auditor; they are never rewritten to match Rust.
"""
import argparse,importlib.util,json,hashlib,subprocess,struct
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
SOURCE='0aa87c64ffd07fb288a7db8df5c46c30e92ff7fa'
DATA='wacore/src/voip/mlow/testdata/'
spec=importlib.util.spec_from_file_location('fixture_pack',Path(__file__).with_name('pack.py'))
pack=importlib.util.module_from_spec(spec);spec.loader.exec_module(pack)
NAMES=['e2e_vectors','exc_pre_lags','fe_dump','gennoise_params_dump','gennoise_vectors','lsf_quant_io',
       'pitchio_ground_truth','pulse_vectors','rc_vectors','sigmode_ground_truth']

def source(name):return subprocess.run(['git','show',f'{SOURCE}:{DATA}{name}'],cwd=ROOT,check=True,stdout=subprocess.PIPE).stdout

def select(name,records):
 if name=='gennoise_vectors':
  indices=set(range(0,len(records),max(1,len(records)//32)))
  groups={}
  for i,r in enumerate(records):groups.setdefault((r['voiced'],r['sf_pulses']>0,r['ng_in']['prev_voiced']),[]).append(i)
  for group in groups.values():indices.update([group[0],group[-1]])
  return [records[i] for i in sorted(indices)]
 if name in ['exc_pre_lags','gennoise_params_dump']:
  frames=json.loads(source('inbound_capture_frames.json'))
  active=lambda i: bool(bytes.fromhex(frames[i])[0]&0x42)
  packets=set(range(0,len(frames),11))
  for voiced in [0,1]:
   eligible=[r['packet'] for r in records if r['voiced']==voiced and active(r['packet'])]
   assert eligible
   packets.update([eligible[0],eligible[-1]])
  return [r for r in records if r['packet'] in packets]
 return records

def main():
 p=argparse.ArgumentParser(description=__doc__);p.add_argument('--check',action='store_true');p.add_argument('--out',type=Path,default=ROOT/'.derive-mlow/legacy');a=p.parse_args()
 a.out.mkdir(parents=True,exist_ok=True);dest=ROOT/DATA;manifest={}
 for name in NAMES:
  original=source(name+'.json');records=select(name,json.loads(original));tmp=a.out/(name+'.json');tmp.write_text(json.dumps(records,separators=(',',':'))+'\n')
  filename=name+'.cbor.zst';target=a.out/filename;meta=pack.pack(tmp,target)
  meta.update(oracle='C audit',source_revision=SOURCE,source_file=name+'.json',source_sha256=hashlib.sha256(original).hexdigest())
  if a.check:
   actual=subprocess.run(['zstd','-q','-d','-c',str(dest/filename)],check=True,stdout=subprocess.PIPE).stdout
   assert hashlib.sha256(actual).hexdigest()==meta['cbor_sha256'],f'audit corpus drift: {filename}'
  else:(dest/filename).write_bytes(target.read_bytes())
  manifest[filename]=meta
 for filename in ['harm_postfilter_vectors.raw','hp_postfilter_vectors.raw']:
  original=source(filename);raw=original
  if filename=='hp_postfilter_vectors.raw':
   count=struct.unpack_from('<I',original)[0];width=3932
   assert len(original)==4+count*width
   indices=sorted(set(range(0,count,max(1,count//32)))|{count-1})
   raw=struct.pack('<I',len(indices))+b''.join(original[4+i*width:4+(i+1)*width] for i in indices)
  compressed=subprocess.run(['zstd','-q','-19','-T1','-c'],input=raw,check=True,stdout=subprocess.PIPE).stdout
  target=dest/(filename+'.zst')
  if a.check:
   actual=subprocess.run(['zstd','-q','-d','-c',str(target)],check=True,stdout=subprocess.PIPE).stdout
   assert actual==raw,f'audit raw drift: {filename}'
  else:target.write_bytes(compressed)
  manifest[filename+'.zst']={'oracle':'C audit','source_revision':SOURCE,'source_file':filename,'source_sha256':hashlib.sha256(original).hexdigest(),'raw_sha256':hashlib.sha256(raw).hexdigest(),'raw_bytes':len(raw),'packed_bytes':len(compressed)}
 if not a.check:(dest/'packed-fixtures.json').write_text(json.dumps(manifest,indent=2)+'\n')
 print('C audit corpus verified' if a.check else 'C audit corpus packed')
if __name__=='__main__':main()
