//! Native MLOW specification generation, snapshot assembly and pinned verification.
mod assemble;
use anyhow::{Context, Result, ensure};
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use xtask_support::{output_tree, read_json, sha256, write_json};

const J: &str = "JgwtTQVeWPm";
const S: &str = "S_ivh1PriOA";
const J_RUNS: &[&str] = &[
    "mlow_110frames",
    "mlow_120ms",
    "mlow_dtx_off",
    "mlow_fe_trace",
    "mlow_signal_trace",
    "mlow_kernel_trace",
    "mlow_postfilter_trace",
    "mlow_params_trace",
    "mlow_gennoise_trace",
];
const S_RUNS: &[&str] = &["mlow_110frames_s", "mlow_120ms_s"];
fn specs_dir(root: &Path) -> PathBuf {
    root.join("tools/oracle-core/specs")
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct TraceRecipe {
    comment: Vec<String>,
    functions: BTreeMap<String, IndexSelector>,
    captures: Vec<Capture>,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct IndexSelector {
    index_hint: u32,
    expect_body_sha256: String,
}

#[derive(Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
enum CaptureOp {
    CaptureMemory,
    CaptureValue,
}

#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Capture {
    op: CaptureOp,
    func: String,
    instruction: usize,
    local: u32,
    count: usize,
    out: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    at: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    len: Option<u32>,
    #[serde(skip_serializing_if = "Option::is_none")]
    float: Option<bool>,
}

fn trace(root: &Path, kind: &str, count: usize, end: usize) -> Result<Value> {
    let mut catalog: BTreeMap<String, TraceRecipe> =
        serde_json::from_str(include_str!("mlow-recipes.json"))?;
    let mut recipe = catalog.remove(kind).context("unknown MLOW trace kind")?;
    let mut base = read_json(&specs_dir(root).join("mlow_110frames.json"))?;
    base["comment"] = json!(recipe.comment);
    let functions = base["functions"]
        .as_object_mut()
        .context("base functions")?;
    for (name, selector) in recipe.functions {
        functions.insert(name, serde_json::to_value(selector)?);
    }
    for capture in &mut recipe.captures {
        if capture.func == "lsf_core" {
            capture.count = count;
            if capture.instruction != 0 {
                capture.instruction = end;
            }
        }
    }
    let mut captures = recipe
        .captures
        .into_iter()
        .map(serde_json::to_value)
        .collect::<std::result::Result<Vec<_>, _>>()?;
    captures.extend(
        base["steps"]
            .as_array()
            .context("base steps")?
            .iter()
            .cloned(),
    );
    base["steps"] = json!(captures);
    Ok(base)
}
fn generated_specs(root: &Path) -> Result<Vec<(String, Value)>> {
    let mut generated = Vec::new();
    let s_base = read_json(&specs_dir(root).join("mlow_encode_s.json"))?;
    for name in ["mlow_110frames", "mlow_120ms"] {
        let mut spec = read_json(&specs_dir(root).join(format!("{name}.json")))?;
        spec["module"] = s_base["module"].clone();
        spec["functions"] = s_base["functions"].clone();
        spec["comment"] = json!([
            "Generated by cargo xt mlow specs; S layout re-derived from alloc/open/init.",
            "All J output hashes retained: this run must prove complete J/S equivalence."
        ]);
        for step in spec["steps"].as_array_mut().context("steps")? {
            if (step["op"] == "malloc" && step["as"] == "attr")
                || (step["op"] == "fill" && step["ptr"] == "$attr")
            {
                step["len"] = json!(1216);
            }
            if step["op"] == "write"
                && step["ptr"] == "$state"
                && let Some(at @ 8..=100) = step["at"].as_u64()
            {
                step["hex"] = json!(hex::encode((5282u32 - at as u32 / 4).to_le_bytes()));
            }
            if step["op"] == "write" && step["ptr"] == "$codec" {
                let value = match step["at"].as_u64() {
                    Some(12) => Some(1398252u32),
                    Some(20) => Some(1325408u32),
                    _ => None,
                };
                if let Some(value) = value {
                    step["hex"] = json!(hex::encode(value.to_le_bytes()));
                }
            }
            if step["op"] == "read_u32" && step["ptr"] == 1719408 {
                step["ptr"] = json!(1740400);
            }
        }
        generated.push((format!("{name}_s.json"), spec));
    }
    for kind in ["fe", "signal", "kernel", "postfilter", "params", "gennoise"] {
        generated.push((
            format!("mlow_{kind}_trace.json"),
            trace(root, kind, 330, 1099)?,
        ));
    }
    Ok(generated)
}
fn spec_bytes(value: &Value) -> Result<Vec<u8>> {
    // Preserve the locked JSON representation, including optional fields/comments.
    // Parsing the executable schema also rejects invalid recipe-generated programs.
    let _: oracle_core::derive::Spec = serde_json::from_value(value.clone())?;
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    Ok(bytes)
}

pub(crate) fn specs(root: &Path, out: &Path, check: bool) -> Result<()> {
    let lock = read_json(&specs_dir(root).join("mlow.lock.json"))?;
    for (name, value) in generated_specs(root)? {
        let bytes = spec_bytes(&value)?;
        let run = name.trim_end_matches(".json");
        ensure!(
            lock["runs"][run]["spec_sha256"].as_str() == Some(sha256(&bytes).as_str()),
            "generated spec differs from locked expansion: {name}"
        );
        if !check {
            xtask_support::write(&out.join(name), &bytes)?;
        }
    }
    Ok(())
}

#[derive(Clone, Copy, PartialEq, Eq)]
pub(crate) enum VerifyMode {
    Execute,
    Cached,
    UpdateLock,
    RefreshSpecHashes,
}

pub(crate) fn fetch(root: &Path, captures: Option<&[&str]>) -> Result<()> {
    let lock = read_json(&root.join("tools/oracle-core/wasm.lock.json"))?;
    let wanted = lock["modules"]
        .as_array()
        .context("capture modules")?
        .iter()
        .filter(|module| {
            captures.is_none_or(|captures| {
                module["fileName"]
                    .as_str()
                    .is_some_and(|name| captures.contains(&name.trim_end_matches(".wasm")))
            })
        })
        .cloned()
        .collect::<Vec<_>>();
    let wanted: Vec<wa_store::capture::WasmCapture> = serde_json::from_value(Value::Array(wanted))?;
    let sources: Vec<wa_store::capture::ReleaseSource> =
        serde_json::from_value(lock["sources"].clone())?;
    wa_store::capture::restore_captures(&wanted, &sources, &root.join(".cache/wa-wasm"))
}

pub(crate) fn verify(root: &Path, out: &Path, capture: &str, mode: VerifyMode) -> Result<()> {
    let cached = mode == VerifyMode::Cached;
    let update = mode == VerifyMode::UpdateLock;
    let refresh = mode == VerifyMode::RefreshSpecHashes;
    ensure!(
        !(update || refresh) || capture == "all",
        "lock refresh requires both captures"
    );
    let specs_root = specs_dir(root);
    let expanded_root = root.join(".derive-mlow/specs");
    if !update && !refresh {
        specs(root, &expanded_root, true)?;
    }
    for (name, value) in generated_specs(root)? {
        xtask_support::write(&expanded_root.join(name), &spec_bytes(&value)?)?;
    }
    let expected = read_json(&specs_root.join("mlow.lock.json"))?;
    let inputs = json!({"synth_mic.raw":sha256(&std::fs::read(specs_root.join("synth_mic.raw"))?),"synth120_head.raw":sha256(&std::fs::read(specs_root.join("synth120_head.raw"))?)});
    if !update {
        ensure!(inputs == expected["inputs"], "synthetic input drift");
    }
    let mut actual = json!({"schema":1,"inputs":inputs,"runs":{}});
    let captures = if capture == "all" {
        vec![J, S]
    } else {
        vec![capture]
    };
    if !cached {
        fetch(root, Some(&captures))?;
    }
    // Specs retain repository-relative input paths; no shell or subprocess needs to interpret them.
    let previous_dir = std::env::current_dir()?;
    std::env::set_current_dir(root)?;
    let result = (|| -> Result<()> {
        for id in captures {
            for name in if id == J { J_RUNS } else { S_RUNS } {
                let run = out.join(name);
                let expanded = expanded_root.join(format!("{name}.json"));
                let spec_path = if S_RUNS.contains(name) || name.ends_with("_trace") {
                    expanded
                } else {
                    specs_root.join(format!("{name}.json"))
                };
                if !update && !refresh {
                    let source = std::fs::read(&spec_path)?;
                    ensure!(
                        expected["runs"][name]["spec_sha256"].as_str()
                            == Some(sha256(&source).as_str()),
                        "current spec differs from lock: {name}"
                    );
                }
                if !cached {
                    oracle_core::derive::run_spec(
                        &spec_path,
                        &root.join(format!(".cache/wa-wasm/{id}.wasm")),
                        &run,
                    )?;
                }
                let manifest = read_json(&run.join("manifest.json"))?;
                let record = json!({"module":manifest["module"],"spec_sha256":manifest["spec_sha256"],"resolutions":manifest["resolutions"],"outputs":manifest["outputs"].as_array().context("outputs")?.len(),"tree_sha256":output_tree(&manifest,&run)?});
                if refresh {
                    for key in ["module", "resolutions", "outputs", "tree_sha256"] {
                        ensure!(
                            record[key] == expected["runs"][name][key],
                            "oracle output drift during serialization migration: {name}/{key}"
                        );
                    }
                } else if !update {
                    ensure!(record == expected["runs"][name], "derivation drift: {name}");
                }
                actual["runs"][name] = record;
                println!("{id}: {name}: verified");
            }
        }
        if capture == "all" || capture == J {
            assemble::all(out)?;
        }
        if update || refresh {
            write_json(&specs_root.join("mlow.lock.json"), &actual)?;
        }
        Ok(())
    })();
    std::env::set_current_dir(previous_dir)?;
    result
}
pub(crate) fn spec(root: &Path, kind: &str, out: &Path, count: usize, end: usize) -> Result<()> {
    write_json(out, &trace(root, kind, count, end)?)
}

pub(crate) fn assemble(
    kind: Option<&str>,
    run: Option<&Path>,
    out: &Path,
    secondary: Option<&Path>,
    count: usize,
) -> Result<()> {
    if let Some(kind) = kind {
        assemble::one(
            kind,
            run.context("--run is required for a single trace")?,
            out,
            secondary,
            count,
        )
    } else {
        assemble::all(&std::path::absolute(out)?)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn recipes_reproduce_every_locked_expansion() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        specs(&root, &root.join(".derive-mlow/specs"), true).unwrap();
    }
}
