//! Auto-generated AppState known verbs (log gating) (WhatsApp 2.3000.1045368834). DO NOT EDIT.
//!

//! Declared syncd action names for log gating. Shares its arms with
//! `wacore-appstate`'s registry (see `emit::appstate::log_gate_matcher`);
//! a `match` over string literals, never `Schema` records.
#![allow(clippy::all)]

pub(crate) fn is_known_wire_name(name: &str) -> bool {
    match name {
        "agentChatAssignment" => true,
        "agentChatAssignmentOpenedStatus" => true,
        "ai_thread_delete" => true,
        "ai_thread_rename" => true,
        "android_unsupported_actions" => true,
        "archive" => true,
        "avatar_updated_action" => true,
        "biz_ai_settings_nudge" => true,
        "bot_welcome_request" => true,
        "business_broadcast_campaign" => true,
        "business_broadcast_insights_sync" => true,
        "business_broadcast_list" => true,
        "call_log" => true,
        "clearChat" => true,
        "contact" => true,
        "ctwaPerCustomerDataSharing" => true,
        "custom_payment_methods" => true,
        "customer_data" => true,
        "deleteChat" => true,
        "deleteMessageForMe" => true,
        "detected_outcomes_status_action" => true,
        "deviceAgent" => true,
        "external_web_beta" => true,
        "favoriteSticker" => true,
        "favorites" => true,
        "interactive_message_action" => true,
        "label_edit" => true,
        "label_jid" => true,
        "label_reordering" => true,
        "label_sublist" => true,
        "lid_contact" => true,
        "lock" => true,
        "markChatAsRead" => true,
        "marketingMessage" => true,
        "marketingMessageBroadcast" => true,
        "merchant_payment_partner" => true,
        "mute" => true,
        "nct_salt_sync" => true,
        "note_edit" => true,
        "nux" => true,
        "out_contact" => true,
        "payment_info" => true,
        "payment_tos" => true,
        "pin_v1" => true,
        "pnForLidChat" => true,
        "primary_feature" => true,
        "primary_version" => true,
        "quick_reply" => true,
        "removeRecentSticker" => true,
        "sentinel" => true,
        "setting_chatLock" => true,
        "setting_disableLinkPreviews" => true,
        "setting_locale" => true,
        "setting_pushName" => true,
        "setting_relayAllCalls" => true,
        "setting_unarchiveChats" => true,
        "settings_sync" => true,
        "shareOwnPn" => true,
        "star" => true,
        "status_privacy" => true,
        "subscriptions_sync_v2" => true,
        "thread_pin" => true,
        "time_format" => true,
        "userStatusMute" => true,
        "waffle_account_link_state" => true,
        "wasa_root_secret" => true,
        _ => false,
    }
}
